
"""

bd

Revision ID: baff89a0f588
Revises: 4370a7dc2054
Create Date: 2025-12-18 10:58:41.343461

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baff89a0f588'
down_revision: Union[str, Sequence[str], None] = '4370a7dc2054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
     # ### commands auto generated by Alembic - please adjust! 
    op.create_table('listcontact',
    sa.Column('id', sa.Integer(), nullable=False,),
    sa.Column('list_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listcontact_list_name'), 'listcontact', ['list_name'], unique=True)
    op.drop_index(op.f('ix_contactlist_nom_liste'), table_name='contactlist')
    op.drop_table('contactlist')
    op.add_column('contact', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contact', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contact', sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contact', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contact', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contact', sa.Column('favorite', sa.Boolean(), nullable=False))
    op.add_column('contact', sa.Column('Blocked', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('contact_numero_key'), 'contact', type_='unique')
    op.drop_index(op.f('ix_contact_nom'), table_name='contact')
    op.create_index(op.f('ix_contact_address'), 'contact', ['address'], unique=False)
    op.create_index(op.f('ix_contact_company'), 'contact', ['company'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_unique_constraint(None, 'contact', ['phone'])
    op.drop_column('contact', 'numero')
    op.drop_column('contact', 'statut')
    op.drop_column('contact', 'adresse')
    op.drop_column('contact', 'nom')
    op.drop_column('contact', 'photo')
    op.add_column('contactlistlink', sa.Column('list_id', sa.Integer(), nullable=False , ))
    op.drop_constraint(op.f('contactlistlink_liste_id_fkey'), 'contactlistlink', type_='foreignkey',)
    op.create_foreign_key(None, 'contactlistlink', 'listcontact', ['list_id'], ['id'], ondelete="delete")
    op.drop_column('contactlistlink', 'liste_id') """
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactlistlink', sa.Column('liste_id', sa.INTEGER(), autoincrement=False, nullable=False,))
    op.drop_constraint("", 'contactlistlink', type_='foreignkey')
    op.create_foreign_key(op.f('contactlistlink_liste_id_fkey'), 'contactlistlink', 'contactlist', ['liste_id'], ['id'])
    op.drop_column('contactlistlink', 'list_id')
    op.add_column('contact', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contact', sa.Column('adresse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('statut', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contact', sa.Column('numero', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint("", 'contact', type_='unique')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_company'), table_name='contact')
    op.drop_index(op.f('ix_contact_address'), table_name='contact')
    op.create_index(op.f('ix_contact_nom'), 'contact', ['nom'], unique=False)
    op.create_unique_constraint(op.f('contact_numero_key'), 'contact', ['numero'], postgresql_nulls_not_distinct=False)
    op.drop_column('contact', 'Blocked')
    op.drop_column('contact', 'favorite')
    op.drop_column('contact', 'image_url')
    op.drop_column('contact', 'phone')
    op.drop_column('contact', 'company')
    op.drop_column('contact', 'address')
    op.drop_column('contact', 'name')
    op.create_table('contactlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_liste', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('contactlist_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contactlist_pkey')))
    op.create_index(op.f('ix_contactlist_nom_liste'), 'contactlist', ['nom_liste'], unique=True)
    op.drop_index(op.f('ix_listcontact_list_name'), table_name='listcontact',)
    op.drop_table('listcontact')
    # ### end Alembic commands ###
"""